In [17]:
import pandas as pd

In [18]:
levels_2 = 'levels_dataset_2017_01_01-2020_12_31.csv'
levels_1 = 'levels_dataset_2021_01_01-2024_12_31.csv'

ml_2 = 'ml_dataset_2017_01_01-2020_12_31.csv'
ml_1 = 'ml_dataset_2021_01_01-2024_12_31.csv'

In [19]:
# Read the CSV files into DataFrames
levels_1_df = pd.read_csv(levels_1)
levels_2_df = pd.read_csv(levels_2)

# Concatenate the DataFrames
levels_dataset = pd.concat([levels_1_df, levels_2_df], axis=0)

# Reset the index
levels_dataset.reset_index(drop=True, inplace=True)

In [20]:
# Display the concatenated DataFrame
levels_dataset.head()

,price_level,level_type,timeframe,created_at,source,anchor_time,completion_time,direction,period
0,15476.00,Fractal_Low,daily,2022-11-21,fractal,NaN,NaN,NaN,NaN
1,15588.00,Fractal_Low,daily,2022-11-09,fractal,NaN,NaN,NaN,NaN
2,15754.00,VP_vah,daily,NaN,volume_profile,NaN,NaN,NaN,2022-11-10
3,15781.29,HTF_Level_daily,daily,2022-11-22,htf,NaN,NaN,NaN,NaN
4,15805.00,VP_vah,daily,NaN,volume_profile,NaN,NaN,NaN,2022-11-22

In [21]:
levels_dataset.to_csv('levels_dataset.csv', index=False)

In [22]:
# Read the CSV files into DataFrames
ml_1_df = pd.read_csv(ml_1)
ml_2_df = pd.read_csv(ml_2)

# Concatenate the DataFrames
ml_dataset = pd.concat([ml_1_df, ml_2_df], axis=0)

# Reset the index
ml_dataset.reset_index(drop=True, inplace=True)

In [23]:
# Display the concatenated DataFrame
ml_dataset.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore,bearish_fractal,bullish_fractal
0,2021-01-01 00:00:00,28923.63,29031.34,28690.17,28995.13,2311.811445,2021-01-01 00:59:59.999,6.676883e+07,58389,1215.359238,3.510354e+07,0,False,False
1,2021-01-01 01:00:00,28995.13,29470.00,28960.35,29409.99,5403.068471,2021-01-01 01:59:59.999,1.583578e+08,103896,3160.041701,9.261399e+07,0,False,False
2,2021-01-01 02:00:00,29410.00,29465.26,29120.03,29194.65,2384.231560,2021-01-01 02:59:59.999,6.984265e+07,57646,1203.433506,3.525275e+07,0,False,False
3,2021-01-01 03:00:00,29195.25,29367.00,29150.02,29278.40,1461.345077,2021-01-01 03:59:59.999,4.276078e+07,42510,775.915666,2.270555e+07,0,False,False
4,2021-01-01 04:00:00,29278.41,29395.00,29029.40,29220.31,2038.046803,2021-01-01 04:59:59.999,5.961464e+07,55414,1003.342834,2.934638e+07,0,False,True

In [24]:
ml_dataset.to_csv('ml_dataset.csv', index=False)

In [24]:
import pandas as pd
filename = 'levels_dataset.csv'
df_levels = pd.read_csv(filename)

In [25]:
df_levels.head()

,price_level,level_type,timeframe,created_at,source,anchor_time,completion_time,direction,period
0,2817.00,Fractal_Low,daily,2017-09-15,fractal,NaN,NaN,NaN,NaN
1,2888.00,VP_vah,daily,NaN,volume_profile,NaN,NaN,NaN,2017-09-15
2,3111.00,VP_poc,daily,NaN,volume_profile,NaN,NaN,NaN,2017-09-15
3,3143.55,Fib_0.75_daily,daily,2017-09-18,fibonacci,2017-09-15,2017-09-18,low_to_high,NaN
4,3156.26,Fractal_Low,daily,2018-12-15,fractal,NaN,NaN,NaN,NaN

In [26]:
df_levels = df_levels[df_levels['created_at'] >= '2017-09-16'].copy()
df_levels.to_csv('levels_dataset.csv', index=False)

In [15]:
import pandas as pd
filename = 'ml_dataset.csv'
df_ml = pd.read_csv(filename)

In [16]:
df_ml.head()

,open_time,open,high,low,close,volume,close_time,quote_asset_volume,number_of_trades,taker_buy_base_asset_volume,taker_buy_quote_asset_volume,ignore,bearish_fractal,bullish_fractal
0,2017-08-17 04:00:00,4261.48,4313.62,4261.32,4308.83,47.181009,2017-08-17 04:59:59.999,202366.138393,171,35.160503,150952.477943,0,False,False
1,2017-08-17 05:00:00,4308.83,4328.69,4291.37,4315.32,23.234916,2017-08-17 05:59:59.999,100304.823567,102,21.448071,92608.279728,0,False,False
2,2017-08-17 06:00:00,4330.29,4345.45,4309.37,4324.35,7.229691,2017-08-17 06:59:59.999,31282.312670,36,4.802861,20795.317224,0,False,False
3,2017-08-17 07:00:00,4316.62,4349.99,4287.41,4349.99,4.443249,2017-08-17 07:59:59.999,19241.058300,25,2.602292,11291.347015,0,False,True
4,2017-08-17 08:00:00,4333.32,4377.85,4333.32,4360.69,0.972807,2017-08-17 08:59:59.999,4239.503586,28,0.814655,3552.746817,0,False,False

In [17]:
df_ml = df_ml[df_ml['open_time'] >= '2017-09-16 00:00:00'].copy()

In [18]:
df_ml.to_csv('ml_dataset.csv', index=False)